In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\monit\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (3.3.4)
Requirement already satisfied: numpy>=1.16.2 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (1.20.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (1.6.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (1.2.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (0.24.1)
Requirement already satisfied: setuptools in c:\users\monit\anaconda3\lib\site-packages (from mlxtend) (52.0.0.post20210125)
Requirement already satisfied: pillow>=6.2.0 in c:\users\monit\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\monit\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\monit\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\monit\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\monit\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: six in c:\users\monit\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\monit\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\monit\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

## Using books dataset

In [2]:
book_data = pd.read_csv('book (2).csv')
book_data

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1
1996,0,0,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,0
1998,0,0,1,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,0

## Apriori algorithm

In [3]:
freq_itemsets1 = apriori(book_data, min_support=0.1, use_colnames=True)
freq_itemsets1

    support                       itemsets
0    0.4230                     (ChildBks)
1    0.2475                     (YouthBks)
2    0.4310                      (CookBks)
3    0.2820                     (DoItYBks)
4    0.2145                       (RefBks)
5    0.2410                       (ArtBks)
6    0.2760                      (GeogBks)
7    0.1135                     (ItalCook)
8    0.1085                     (Florence)
9    0.1650           (ChildBks, YouthBks)
10   0.2560            (ChildBks, CookBks)
11   0.1840           (ChildBks, DoItYBks)
12   0.1515             (ChildBks, RefBks)
13   0.1625             (ChildBks, ArtBks)
14   0.1950            (ChildBks, GeogBks)
15   0.1620            (CookBks, YouthBks)
16   0.1155           (DoItYBks, YouthBks)
17   0.1010             (YouthBks, ArtBks)
18   0.1205            (YouthBks, GeogBks)
19   0.1875            (CookBks, DoItYBks)
20   0.1525              (CookBks, RefBks)
21   0.1670              (CookBks, ArtBks)
22   0.1925             (CookBks, GeogBks)
23   0.1135            (ItalCook, CookBks)
24   0.1055             (DoItYBks, RefBks)
25   0.1235             (DoItYBks, ArtBks)
26   0.1325            (DoItYBks, GeogBks)
27   0.1105              (RefBks, GeogBks)
28   0.1275              (ArtBks, GeogBks)
29   0.1290  (ChildBks, CookBks, YouthBks)
30   0.1460  (ChildBks, CookBks, DoItYBks)
31   0.1225    (ChildBks, CookBks, RefBks)
32   0.1265    (ChildBks, CookBks, ArtBks)
33   0.1495   (ChildBks, CookBks, GeogBks)
34   0.1045  (ChildBks, DoItYBks, GeogBks)
35   0.1020    (ChildBks, ArtBks, GeogBks)
36   0.1015    (CookBks, DoItYBks, ArtBks)
37   0.1085   (CookBks, DoItYBks, GeogBks)
38   0.1035     (CookBks, ArtBks, GeogBks)

In [5]:
rule_1 = association_rules(freq_itemsets1, metric="lift", min_threshold=0.7)
rule_1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ChildBks),(YouthBks),0.4230,0.2475,0.1650,0.390071,1.576044,0.060308,1.233750
1,(YouthBks),(ChildBks),0.2475,0.4230,0.1650,0.666667,1.576044,0.060308,1.731000
2,(ChildBks),(CookBks),0.4230,0.4310,0.2560,0.605201,1.404179,0.073687,1.441240
3,(CookBks),(ChildBks),0.4310,0.4230,0.2560,0.593968,1.404179,0.073687,1.421069
4,(ChildBks),(DoItYBks),0.4230,0.2820,0.1840,0.434988,1.542511,0.064714,1.270770
...,...,...,...,...,...,...,...,...,...
95,"(CookBks, GeogBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
96,"(ArtBks, GeogBks)",(CookBks),0.1275,0.4310,0.1035,0.811765,1.883445,0.048547,3.022812
97,(CookBks),"(ArtBks, GeogBks)",0.4310,0.1275,0.1035,0.240139,1.883445,0.048547,1.148237
98,(ArtBks),"(CookBks, GeogBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
99,(GeogBks),"(CookBks, ArtBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800

In [6]:
rule_1.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
29,(CookBks),(ItalCook),0.4310,0.1135,0.1135,0.263341,2.320186,0.064582,1.203406
28,(ItalCook),(CookBks),0.1135,0.4310,0.1135,1.000000,2.320186,0.064582,inf
76,"(ChildBks, ArtBks)",(GeogBks),0.1625,0.2760,0.1020,0.627692,2.274247,0.057150,1.944628
81,(GeogBks),"(ChildBks, ArtBks)",0.2760,0.1625,0.1020,0.369565,2.274247,0.057150,1.328448
87,(ArtBks),"(CookBks, DoItYBks)",0.2410,0.1875,0.1015,0.421162,2.246196,0.056313,1.403674
82,"(CookBks, DoItYBks)",(ArtBks),0.1875,0.2410,0.1015,0.541333,2.246196,0.056313,1.654797
99,(GeogBks),"(CookBks, ArtBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800
94,"(CookBks, ArtBks)",(GeogBks),0.1670,0.2760,0.1035,0.619760,2.245509,0.057408,1.904063
98,(ArtBks),"(CookBks, GeogBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
95,"(CookBks, GeogBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
52,"(ChildBks, CookBks)",(RefBks),0.2560,0.2145,0.1225,0.478516,2.230842,0.067588,1.506277
57,(RefBks),"(ChildBks, CookBks)",0.2145,0.2560,0.1225,0.571096,2.230842,0.067588,1.734652
80,(ArtBks),"(ChildBks, GeogBks)",0.2410,0.1950,0.1020,0.423237,2.170444,0.055005,1.395719
77,"(ChildBks, GeogBks)",(ArtBks),0.1950,0.2410,0.1020,0.523077,2.170444,0.055005,1.591452
86,(DoItYBks),"(CookBks, ArtBks)",0.2820,0.1670,0.1015,0.359929,2.155264,0.054406,1.301418
83,"(CookBks, ArtBks)",(DoItYBks),0.1670,0.2820,0.1015,0.607784,2.155264,0.054406,1.830626
69,(GeogBks),"(ChildBks, CookBks)",0.2760,0.2560,0.1495,0.541667,2.115885,0.078844,1.623273
64,"(ChildBks, CookBks)",(GeogBks),0.2560,0.2760,0.1495,0.583984,2.115885,0.078844,1.740319
93,(GeogBks),"(CookBks, DoItYBks)",0.2760,0.1875,0.1085,0.393116,2.096618,0.056750,1.338806
88,"(CookBks, DoItYBks)",(GeogBks),0.1875,0.2760,0.1085,0.578667,2.096618,0.056750,1.718354

In [8]:
rule_1[rule_1.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ChildBks),(YouthBks),0.4230,0.2475,0.1650,0.390071,1.576044,0.060308,1.233750
1,(YouthBks),(ChildBks),0.2475,0.4230,0.1650,0.666667,1.576044,0.060308,1.731000
2,(ChildBks),(CookBks),0.4230,0.4310,0.2560,0.605201,1.404179,0.073687,1.441240
3,(CookBks),(ChildBks),0.4310,0.4230,0.2560,0.593968,1.404179,0.073687,1.421069
4,(ChildBks),(DoItYBks),0.4230,0.2820,0.1840,0.434988,1.542511,0.064714,1.270770
...,...,...,...,...,...,...,...,...,...
95,"(CookBks, GeogBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
96,"(ArtBks, GeogBks)",(CookBks),0.1275,0.4310,0.1035,0.811765,1.883445,0.048547,3.022812
97,(CookBks),"(ArtBks, GeogBks)",0.4310,0.1275,0.1035,0.240139,1.883445,0.048547,1.148237
98,(ArtBks),"(CookBks, GeogBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
99,(GeogBks),"(CookBks, ArtBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800

In [9]:
freq_itemsets2 = apriori(book_data, min_support=0.2, use_colnames=True)
freq_itemsets2

   support             itemsets
0   0.4230           (ChildBks)
1   0.2475           (YouthBks)
2   0.4310            (CookBks)
3   0.2820           (DoItYBks)
4   0.2145             (RefBks)
5   0.2410             (ArtBks)
6   0.2760            (GeogBks)
7   0.2560  (ChildBks, CookBks)

In [10]:
rule_2 = association_rules(freq_itemsets2, metric="lift", min_threshold=1)
rule_2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ChildBks),(CookBks),0.423,0.431,0.256,0.605201,1.404179,0.073687,1.441240
1,(CookBks),(ChildBks),0.431,0.423,0.256,0.593968,1.404179,0.073687,1.421069

In [11]:
freq_itemsets3 = apriori(book_data, min_support=0.3, use_colnames=True)
freq_itemsets3

   support    itemsets
0    0.423  (ChildBks)
1    0.431   (CookBks)

In [12]:
rule_3 = association_rules(freq_itemsets3, metric="lift", min_threshold=0.5)
rule_3

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

# -----------------------------------------------------------------------------------------

## Using Movies dataset

In [16]:
import pandas as pd

In [14]:
mov_data = pd.read_csv('my_movies (1).csv')
mov_data.shape

(10, 15)

In [15]:
m_data=pd.get_dummies(mov_data)
m_data.head()

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [18]:
freq_itemsets1 = apriori(m_data, min_support=0.5, use_colnames=True)
freq_itemsets1

    support                                        itemsets
0       0.6                                   (Sixth Sense)
1       0.7                                     (Gladiator)
2       0.6                                       (Patriot)
3       0.6                                  (V1_Gladiator)
4       0.6                                    (V2_Patriot)
5       0.5                        (Gladiator, Sixth Sense)
6       0.6                            (Gladiator, Patriot)
7       0.6                       (Gladiator, V1_Gladiator)
8       0.6                         (Gladiator, V2_Patriot)
9       0.6                         (V1_Gladiator, Patriot)
10      0.6                           (Patriot, V2_Patriot)
11      0.6                      (V1_Gladiator, V2_Patriot)
12      0.6              (Gladiator, V1_Gladiator, Patriot)
13      0.6                (Gladiator, Patriot, V2_Patriot)
14      0.6           (Gladiator, V1_Gladiator, V2_Patriot)
15      0.6             (V1_Gladiator, Patriot, V2_Patriot)
16      0.6  (Gladiator, V1_Gladiator, Patriot, V2_Patriot)

In [22]:
rules1 = association_rules(freq_itemsets1, metric="lift", min_threshold=1)
rules1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
2,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
3,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
4,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
5,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
6,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
7,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
8,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
13,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
15,"(Gladiator, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,"(V1_Gladiator, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
17,(Gladiator),"(V1_Gladiator, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
18,(V1_Gladiator),"(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
19,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
20,"(Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
21,"(Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,"(Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
23,(Gladiator),"(Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
24,(Patriot),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
25,(V2_Patriot),"(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
26,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
27,"(Gladiator, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,"(V1_Gladiator, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
29,(Gladiator),"(V1_Gladiator, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
30,(V1_Gladiator),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,"(Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(Gladiator, V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
39,"(Gladiator, V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(Gladiator, Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(V1_Gladiator, Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
42,"(Gladiator, V1_Gladiator)","(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(Gladiator, Patriot)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(Gladiator, V2_Patriot)","(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(V1_Gladiator, Patriot)","(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,"(V1_Gladiator, V2_Patriot)","(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,"(Patriot, V2_Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(Gladiator),"(V1_Gladiator, Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
49,(V1_Gladiator),"(Gladiator, Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
50,(Patriot),"(Gladiator, V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
51,(V2_Patriot),"(Gladiator, V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf

In [24]:
rules1.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
26,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
38,"(Gladiator, V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,"(Gladiator, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,(V1_Gladiator),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
31,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,"(Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
39,"(Gladiator, V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
24,(Patriot),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(Gladiator, Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
42,"(Gladiator, V1_Gladiator)","(Patriot, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
43,"(Gladiator, Patriot)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(Gladiator, V2_Patriot)","(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(V1_Gladiator, Patriot)","(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
46,"(V1_Gladiator, V2_Patriot)","(Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
47,"(Patriot, V2_Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [25]:
rules1[rules1.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
2,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
3,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
4,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
5,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
6,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
7,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
8,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
13,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
15,"(Gladiator, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,"(V1_Gladiator, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
17,(Gladiator),"(V1_Gladiator, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
18,(V1_Gladiator),"(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
19,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
20,"(Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
21,"(Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,"(Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
23,(Gladiator),"(Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
24,(Patriot),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
25,(V2_Patriot),"(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
26,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
27,"(Gladiator, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,"(V1_Gladiator, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
29,(Gladiator),"(V1_Gladiator, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
30,(V1_Gladiator),"(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,"(Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(Gladiator, V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
39,"(Gladiator, V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(Gladiator, Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(V1_Gladiator, Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
42,"(Gladiator, V1_Gladiator)","(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(Gladiator, Patriot)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(Gladiator, V2_Patriot)","(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(V1_Gladiator, Patriot)","(Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,"(V1_Gladiator, V2_Patriot)","(Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,"(Patriot, V2_Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(Gladiator),"(V1_Gladiator, Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
49,(V1_Gladiator),"(Gladiator, Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
50,(Patriot),"(Gladiator, V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
51,(V2_Patriot),"(Gladiator, V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf

In [20]:
freq_itemsets2 = apriori(m_data, min_support=0.1, use_colnames=True)
freq_itemsets2

      support                                           itemsets
0         0.6                                      (Sixth Sense)
1         0.7                                        (Gladiator)
2         0.2                                            (LOTR1)
3         0.2                                    (Harry Potter1)
4         0.6                                          (Patriot)
...       ...                                                ...
1392      0.1  (V4_Green Mile, V1_Sixth Sense, Green Mile, Si...
1393      0.1  (V4_Green Mile, V1_Sixth Sense, Green Mile, Si...
1394      0.1  (V4_Green Mile, V1_Sixth Sense, Green Mile, Si...
1395      0.1  (V4_Green Mile, V1_Sixth Sense, Green Mile, Ha...
1396      0.1  (V4_Green Mile, Green Mile, V1_Sixth Sense, Si...

[1397 rows x 2 columns]

In [23]:
rules2 = association_rules(freq_itemsets2, metric="lift", min_threshold=1)
rules2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.40
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.80
2,(Sixth Sense),(Patriot),0.6,0.6,0.4,0.666667,1.111111,0.04,1.20
3,(Patriot),(Sixth Sense),0.6,0.6,0.4,0.666667,1.111111,0.04,1.20
4,(Sixth Sense),(LOTR),0.6,0.1,0.1,0.166667,1.666667,0.04,1.08
...,...,...,...,...,...,...,...,...,...
64211,(V5_LOTR2),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf
64212,(LOTR1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.2,0.1,0.1,0.500000,5.000000,0.08,1.80
64213,(V2_LOTR1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf
64214,(LOTR2),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.2,0.1,0.1,0.500000,5.000000,0.08,1.80
64215,(V3_Harry Potter1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf

In [26]:
rules2.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
32108,"(LOTR2, V3_Harry Potter1, V5_LOTR2, LOTR1)","(Sixth Sense, Green Mile, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42182,"(LOTR2, V2_LOTR1, V5_LOTR2, Green Mile)","(LOTR1, V1_Sixth Sense, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42170,"(LOTR1, V2_LOTR1, V5_LOTR2, V1_Sixth Sense)","(LOTR2, Green Mile, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42171,"(LOTR2, LOTR1, V5_LOTR2, V1_Sixth Sense)","(V2_LOTR1, Green Mile, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42172,"(LOTR2, V2_LOTR1, V5_LOTR2, V1_Sixth Sense)","(LOTR1, Green Mile, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42173,"(LOTR2, V2_LOTR1, LOTR1, V1_Sixth Sense)","(V5_LOTR2, Green Mile, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42174,"(LOTR1, V5_LOTR2, Green Mile, Harry Potter1)","(LOTR2, V2_LOTR1, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42175,"(V2_LOTR1, V5_LOTR2, Green Mile, Harry Potter1)","(LOTR2, LOTR1, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42176,"(LOTR2, V5_LOTR2, Green Mile, Harry Potter1)","(V2_LOTR1, LOTR1, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42177,"(V2_LOTR1, LOTR1, Green Mile, Harry Potter1)","(LOTR2, V5_LOTR2, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42178,"(LOTR2, LOTR1, Green Mile, Harry Potter1)","(V2_LOTR1, V5_LOTR2, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42179,"(LOTR2, V2_LOTR1, Green Mile, Harry Potter1)","(LOTR1, V5_LOTR2, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42180,"(LOTR1, V2_LOTR1, V5_LOTR2, Green Mile)","(LOTR2, V1_Sixth Sense, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42181,"(LOTR2, LOTR1, V5_LOTR2, Green Mile)","(V2_LOTR1, V1_Sixth Sense, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42183,"(LOTR2, V2_LOTR1, LOTR1, Green Mile)","(V5_LOTR2, V1_Sixth Sense, Harry Potter1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42197,"(LOTR2, V1_Sixth Sense, Harry Potter1)","(LOTR1, V2_LOTR1, V5_LOTR2, Green Mile)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42184,"(V2_LOTR1, V5_LOTR2, LOTR1, Harry Potter1)","(LOTR2, Green Mile, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42185,"(LOTR2, V5_LOTR2, LOTR1, Harry Potter1)","(V2_LOTR1, Green Mile, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42186,"(LOTR2, V5_LOTR2, V2_LOTR1, Harry Potter1)","(LOTR1, Green Mile, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
42187,"(LOTR2, V2_LOTR1, LOTR1, Harry Potter1)","(V5_LOTR2, Green Mile, V1_Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf

In [27]:
rules2[rules2.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.40
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.80
2,(Sixth Sense),(Patriot),0.6,0.6,0.4,0.666667,1.111111,0.04,1.20
3,(Patriot),(Sixth Sense),0.6,0.6,0.4,0.666667,1.111111,0.04,1.20
4,(Sixth Sense),(LOTR),0.6,0.1,0.1,0.166667,1.666667,0.04,1.08
...,...,...,...,...,...,...,...,...,...
64211,(V5_LOTR2),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf
64212,(LOTR1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.2,0.1,0.1,0.500000,5.000000,0.08,1.80
64213,(V2_LOTR1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf
64214,(LOTR2),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.2,0.1,0.1,0.500000,5.000000,0.08,1.80
64215,(V3_Harry Potter1),"(V4_Green Mile, Green Mile, V1_Sixth Sense, Si...",0.1,0.1,0.1,1.000000,10.000000,0.09,inf